#!/usr/bin/env bash

set -e

CONFIG="base"
SUFFIX=".conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}${SUFFIX}" "${@}"

case "$(uname)" in
  Darwin)
    echo "Configuring MacOS"
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "darwin${SUFFIX}" "${@}"
    ;;
  Linux)
    echo "Configuring Linux"
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "linux${SUFFIX}" -p dotbot-sudo/sudo.py -p dotbot_plugin_aptget/aptget.py "${@}"
    ;;
  *)
    echo "Unknown OS: $(uname). Skipping OS specific directives."
    ;;
esac
