export LC_ALL=en_US.UTF-8
export DISABLE_AUTO_TITLE="true"
export CLICOLOR=1
export HISTFILE=$HOME/.zsh/history
export HISTSIZE=10000
export SAVEHIST=10000

export TMUXP_CONFIGDIR="${XDG_CONFIG_HOME}/tmuxp"

if [ "$(uname)" = 'Darwin' ]; then
    export HOMEBREW_AUTO_UPDATE_SECS=86400
fi

